sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nCzTM4xALS5/BQIzxGXzPb0LzJuGa9nxpRXJPs1YvwdBGs7XvMzAiifZNaxCXegheluXIrAWHDP8HahnJZ44oonbvyifh2gyYAh0ng6U5bAdAu9Jm9bGk+irm6OLOcd8/MsiuOLH1m5q9UUFzLlfXHGxeSejAvBMV66HTQFgRPiR6JIgFlpYHvRLoDTCltTN7traCJi8hKCNf/QAvxV52S1fOahKjk1CmwA7bkyhaNvA3Hnh5dSyD/KQJ7rQ/3h38xQegy4U4yEgtiX5mpj6VO0MDofAHv58iVExNgbXu1CwDxdEhb0WHhAdpiIVQo8xeYVAzK2R/urIscnkysUy+8csxTxaGv80X9dbp8H+E8mODnykkm57pda8qQhC/KPxsLlcqBxUCI1U651qF13xkWV9hEF7ua+/RsipAd+rZFio1AWc8FDMwodn/PhbQeDMb7Zc92Qt2nD1dMvKv7rcqZmbouCxCf/tVjKVae6cztTbJxV9FgIb20tJJiujOfpac6fngPZda3s0GbsYdtKg1jC/9FF4ZWMCg8/DMu1RVvhQrWVQncBMJiwb01744UMjpPa114xPgJWuT2gPqKFFqQOEGSenIch4e7m24rvfygtp7eL1vW2sl4Ni3gb9JkDIiM9/sdYmS4DVKizwTbxdVizHhO+mqkAnSxqfYIqETPQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/My-Young-Alcides--A-Faded-Photograph_4347
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy